dpi: 200
min_FOV: 20
star_size:
  limiting_mag: 5.5
  limit_size: 0.01
  power_law: 1.0
line_alpha:
  constellations: 1.0
  bkg_constellations: 0.3
  shadows: 0.3
  ecliptic: 0.5
line_widths:
  scale_factor: 0.006
  constellations: 1.0
  bkg_constellations: 1.0
  shadows: 2.51
  helpers: 1.0
  asterisms: 1.25
  ecliptic: 1.5
  zodiac:
    thin: 1.0
    thick: 4.0
  grid:
    thick: 0.8
    thin: 0.6
  planisphere:
    borders: 1.0
    meridians: 0.6
line_styles:
  constellations: solid
  bkg_constellations: solid
  shadows: solid
  helpers: dotted
  asterisms: solid
  ecliptic: dashed
  planisphere:
    meridians: dotted
    borders: solid
  sky_view:
    horizon: dashed
  polar:
    grid: dashed
  equatorial:
    grid: dashed
stars:
  size_factor:
    card_plot: 200.0
    equatorial: 10.0
    polar: 200.0
    sky_view: 100.0
  line_pad:
    proportional: 1.5
    constant: 0.1
  shadow:
    offset_x: 0.003
    offset_y: 0.003
    size: 2.0
    alpha: 1.0
    line_w: 0.1
  pad:
    size: 1.5
    alpha: 0.8
    line_w: 0.5
  alpha_bkg: 0.8
  alpha_faint: 0.8
  alpha_high: 1.0
star_colormap: stellarium
milky_way:
  mw_levels: 5
  alpha_low: 0.15
  alpha_high: 0.3
zodiac:
  ribbon_width: 1.0
  ribbon_alpha: 0.2
  pad_size: 1.2
  pad_alpha: 0.9
  text_size: 0.8
  thick_spacing: 30
  thin_spacing: 5
colors:
  sky: '#ffffff'
  stars: '#000000'
  star_pad: '#000000'
  milky_way: '#0011ff'
  shadow: '#363636'
  con_lines: '#000000'
  con_lines_shadow: '#000000'
  asterisms: '#32cd32'
  helpers: '#ff7f50'
  horizon: '#ffffff'
  grid: '#ffff00'
  ecliptic: '#8a0000'
  zodiac: '#850000'
  cardinals: '#8b0000'
  border: '#ffd700'
  mater: '#add8e6'
  cardback_1: '#004577'
  cardback_2: '#660000'
  accent_1: '#b8860b'
  accent_2: '#b8860b'
  calendar: '#000000'
  star_names: '#ffd700'
  con_names: '#b85300'
  con_parts: '#ee82ee'
  asterism_labels: '#ff630f'
  ecliptic_label: '#6b0000'
  zodiac_label: '#6b0000'
flags:
  con_lines: true
  con_names: false
  con_parts: false
  asterisms: false
  helpers: false
  star_names: false
  grid: false
  ecliptic: false
  zodiac: true
  milky_way: true
  harey_stars: true
  show: true
  save: false
  star_colors: true
  show_guides: false
  radial_labels: true
fonts:
  labels:
    family: DejaVu Sans
    weight: normal
  cardback:
    family: DejaVu Sans
    weight: bold
  calendar:
    family: DejaVu Sans
    weight: bold
font_sizes:
  card_plot: 10
  equatorial_plot:
    s: 7
    l: 10
  polar_plot:
    s: 7
    l: 10
  sky_view:
    s: 7
    l: 10
sky_view:
  border_size: 0.05
calendar:
  ring_size: 0.1
  bleed_size: 0.2
  line_width: 0.8
  line_style: solid
  labels_pos:
    day: 0.5
    month: 0.5
    hour: 0.55
  day_marker_size: 4
  day_markers: o
  font_widths:
    days: 0.6
    months: 0.8
    hours: 0.8
    circles: 0.0
  cardinals_font_size: 10
  hours_lw: 0.5
  hours_ls: solid
  half_hours_lw: 0.8
  half_hours_ls: dashed
  quarter_hours_lw: 0.4
  quarter_hours_ls: dotted
planisphere:
  hatch: '.....'
