# Constellation names 
text('Orsa Minore', (0.55*canvas.width, 0.57*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Dragone', (0.56*canvas.width, 0.69*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Cassiopeia', (0.27*canvas.width, 0.43*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Cefeo', (0.31*canvas.width, 0.62*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Giraffa', (0.44*canvas.width, 0.31*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Orsa Maggiore', (0.81*canvas.width, 0.41*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Cani da   caccia', (0.94*canvas.width, 0.59*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Leone   minore', (0.95*canvas.width, 0.29*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Lira', (0.40*canvas.width, 0.96*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Cigno', (0.24*canvas.width, 0.86*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Andromeda', (0.04*canvas.width, 0.42*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Lucertola', (0.14*canvas.width, 0.66*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Perseo', (0.26*canvas.width, 0.19*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Auriga', (0.43*canvas.width, 0.09*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Lince', (0.72*canvas.width, 0.19*canvas.height), font_size='9pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Grande Carro', (0.79*canvas.width, 0.53*canvas.height), font_size='8pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ff00')

# Named stars labels
text('Pole Star', (0.50*canvas.width, 0.50*canvas.height), font_size='8pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Algol', (0.20*canvas.width, 0.18*canvas.height), font_size='8pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Capella', (0.43*canvas.width, 0.12*canvas.height), font_size='8pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Cor Caroli', (0.95*canvas.width, 0.61*canvas.height), font_size='8pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Mizar', (0.78*canvas.width, 0.61*canvas.height), font_size='8pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Alcor', (0.78*canvas.width, 0.61*canvas.height), font_size='8pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Thuban', (0.69*canvas.width, 0.61*canvas.height), font_size='8pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Kochab', (0.60*canvas.width, 0.59*canvas.height), font_size='8pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Vega', (0.43*canvas.width, 0.95*canvas.height), font_size='8pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Deneb', (0.24*canvas.width, 0.80*canvas.height), font_size='8pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')

# Ecliptic label
text('eclittica', (0.50*canvas.width, 0.60*canvas.height), font_size='8pt',text_anchor='middle', font_family='Caveat Brush', fill='#dc143c')
