# Constellation names 
text('Orsa Minore', (0.46*canvas.width, 0.32*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Dragone', (0.39*canvas.width, 0.29*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Cassiopeia', (0.62*canvas.width, 0.26*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Cefeo', (0.52*canvas.width, 0.19*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Giraffa', (0.59*canvas.width, 0.36*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Orsa Maggiore', (0.44*canvas.width, 0.46*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Leone', (0.43*canvas.width, 0.60*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Cani da   caccia', (0.36*canvas.width, 0.47*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Leone   minore', (0.46*canvas.width, 0.53*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Bootes', (0.26*canvas.width, 0.44*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Corona Boreale', (0.20*canvas.width, 0.37*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Chioma di Berenice', (0.32*canvas.width, 0.53*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Lira', (0.29*canvas.width, 0.11*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Cigno', (0.41*canvas.width, 0.05*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Ercole', (0.19*canvas.width, 0.21*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Andromeda', (0.74*canvas.width, 0.18*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Triangolo', (0.79*canvas.width, 0.29*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Lucertola', (0.58*canvas.width, 0.08*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Perseo', (0.70*canvas.width, 0.36*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Toro', (0.80*canvas.width, 0.49*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Ariete', (0.84*canvas.width, 0.33*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Gemelli', (0.63*canvas.width, 0.56*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Auriga', (0.66*canvas.width, 0.45*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Cane minore', (0.62*canvas.width, 0.64*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Cancro', (0.54*canvas.width, 0.60*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Lince', (0.54*canvas.width, 0.49*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Orione', (0.75*canvas.width, 0.59*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Cane maggiore', (0.70*canvas.width, 0.78*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Lepre', (0.80*canvas.width, 0.72*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Unicorno', (0.66*canvas.width, 0.66*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Idra', (0.41*canvas.width, 0.73*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Cratere', (0.34*canvas.width, 0.74*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Pompa', (0.41*canvas.width, 0.84*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Vergine', (0.22*canvas.width, 0.62*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Corvo', (0.26*canvas.width, 0.76*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Poppa', (0.64*canvas.width, 0.86*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Vela', (0.48*canvas.width, 0.96*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Bussola', (0.56*canvas.width, 0.86*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Colomba', (0.79*canvas.width, 0.86*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')
text('Sestante', (0.45*canvas.width, 0.68*canvas.height), font_size='7pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ffff')

# Constellation parts labels
text('Guardiani', (0.42*canvas.width, 0.33*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('zampe', (0.44*canvas.width, 0.25*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('testa', (0.34*canvas.width, 0.23*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('coda', (0.39*canvas.width, 0.29*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('coda', (0.40*canvas.width, 0.36*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('puntatori', (0.45*canvas.width, 0.44*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('testa', (0.37*canvas.width, 0.42*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('zampe', (0.43*canvas.width, 0.52*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('zampe', (0.48*canvas.width, 0.50*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('groppa', (0.50*canvas.width, 0.46*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('testa', (0.48*canvas.width, 0.58*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('coda', (0.37*canvas.width, 0.59*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('corpo', (0.21*canvas.width, 0.47*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('testa', (0.26*canvas.width, 0.41*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('pipa', (0.33*canvas.width, 0.40*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('ala', (0.41*canvas.width, 0.11*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('piede', (0.47*canvas.width, 0.04*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('Chiave di volta', (0.22*canvas.width, 0.27*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('clava', (0.28*canvas.width, 0.28*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('catene', (0.65*canvas.width, 0.12*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('testa', (0.77*canvas.width, 0.49*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('corno', (0.72*canvas.width, 0.49*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('corno', (0.78*canvas.width, 0.45*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('coda', (0.87*canvas.width, 0.46*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('testa', (0.86*canvas.width, 0.29*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('coda', (0.81*canvas.width, 0.35*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('cintura', (0.76*canvas.width, 0.63*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('mazza', (0.69*canvas.width, 0.56*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('scudo', (0.79*canvas.width, 0.56*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('testa', (0.54*canvas.width, 0.66*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('coda', (0.22*canvas.width, 0.80*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('testa', (0.31*canvas.width, 0.64*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('piedi', (0.13*canvas.width, 0.57*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('becco', (0.26*canvas.width, 0.73*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('piede', (0.25*canvas.width, 0.77*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('coda', (0.28*canvas.width, 0.78*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('testa', (0.13*canvas.width, 0.39*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('Pesce Settentrionale', (0.83*canvas.width, 0.21*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('coda', (0.93*canvas.width, 0.42*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('poppa', (0.63*canvas.width, 0.81*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('testa', (0.82*canvas.width, 0.85*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('coda', (0.77*canvas.width, 0.85*canvas.height), font_size='5pt', text_anchor='middle', font_family='Caveat Brush', fill='#ee82ee')
text('Grande Carro', (0.41*canvas.width, 0.43*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ff00')
text('Diamante della  vergine', (0.26*canvas.width, 0.58*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ff00')
text('Grande esagono', (0.68*canvas.width, 0.57*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ff00')
text('testa del serpente', (0.06*canvas.width, 0.42*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#00ff00')

# Named stars labels
text('Pole Star', (0.50*canvas.width, 0.32*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Algol', (0.73*canvas.width, 0.35*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Pleiades', (0.79*canvas.width, 0.43*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Aldebaran', (0.78*canvas.width, 0.50*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Rigel', (0.81*canvas.width, 0.65*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Capella', (0.65*canvas.width, 0.43*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Betelgeuse', (0.72*canvas.width, 0.60*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Sirio', (0.70*canvas.width, 0.74*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Castor', (0.59*canvas.width, 0.54*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Procyon', (0.61*canvas.width, 0.65*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Pollux', (0.58*canvas.width, 0.55*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Alphard', (0.49*canvas.width, 0.72*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Regolo', (0.45*canvas.width, 0.63*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Denebola', (0.35*canvas.width, 0.59*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Cor Caroli', (0.34*canvas.width, 0.47*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Mizar', (0.38*canvas.width, 0.41*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Spica', (0.19*canvas.width, 0.67*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Alcor', (0.38*canvas.width, 0.41*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Thuban', (0.40*canvas.width, 0.37*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Arcturus', (0.22*canvas.width, 0.49*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Kochab', (0.43*canvas.width, 0.33*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Gemma', (0.20*canvas.width, 0.38*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Vega', (0.28*canvas.width, 0.14*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')
text('Deneb', (0.45*canvas.width, 0.07*canvas.height), font_size='6pt', text_anchor='middle', font_family='Caveat Brush', fill='#ffd700')

# Ecliptic label
text('eclittica', (0.42*canvas.width, 0.66*canvas.height), font_size='6pt',text_anchor='middle', font_family='Caveat Brush', fill='#dc143c')

# Horizon label
text('orizzonte', (0.50*canvas.width, 0.93*canvas.height), font_size='6pt',text_anchor='middle', font_family='Caveat Brush', fill='#ffffff')
